// GENERATED by tools/fit_spawn.py from reference/dumps/explore_goal_locations_large (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-24, -23, 0.85, 255, 238, 255],
  [-23, -19, 0.95, 249, 255, 255],
  [19, 23, 0.85, 254, 208, 255]
];
