// GENERATED by tools/fit_spawn.py from reference/dumps/explore_object_locations_large (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-14, -13, 0.75, 255, 255, 255],
  [-13, -12, 0.95, 229, 255, 255],
  [14, 16, 0.9, 255, 208, 255],
  [26, 32, 0.9, 255, 219, 255]
];
