// GENERATED by tools/fit_spawn.py from reference/dumps/explore_obstructed_goals_small (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-24, -23, 0.9, 253, 255, 255],
  [-23, -19, 1.0, 242, 255, 255],
  [19, 23, 0.9, 255, 225, 255]
];
