// GENERATED by tools/fit_spawn.py from reference/dumps/explore_obstructed_goals_large (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-14, -13, 0.8, 247, 220, 255],
  [-13, -12, 0.85, 242, 245, 255],
  [15, 16, 0.9, 226, 200, 255],
  [26, 28, 0.9, 255, 208, 255],
  [28, 31, 0.85, 255, 207, 255],
  [31, 32, 0.95, 255, 214, 255]
];
