// GENERATED by tools/fit_spawn.py from reference/dumps/language_select_described_object (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-24, -19, 1.0, 241, 255, 255],
  [19, 23, 1.0, 255, 222, 242]
];
