// GENERATED by tools/fit_spawn.py from reference/dumps/language_answer_quantitative_question (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-24, -19, 1.0, 241, 255, 255],
  [-3, -2, 0.3, 236, 235, 212],
  [-1, 0, 0.25, 245, 251, 223]
];
