// GENERATED by tools/fit_spawn.py from reference/dumps/rooms_collect_good_objects_train (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-10, -9, 0.65, 242, 224, 255],
  [17, 20, 1.0, 255, 227, 240],
  [29, 31, 0.95, 255, 231, 255],
  [31, 32, 1.0, 255, 228, 246]
];
