// GENERATED by tools/fit_spawn.py from reference/dumps/rooms_keys_doors_puzzle (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-13, -12, 0.7, 255, 255, 255],
  [14, 15, 0.8, 231, 216, 255],
  [15, 16, 0.85, 218, 212, 255],
  [26, 27, 0.7, 255, 217, 255],
  [27, 29, 0.75, 255, 218, 255],
  [29, 30, 0.8, 255, 213, 255],
  [30, 31, 0.85, 255, 214, 249],
  [31, 32, 1.0, 255, 201, 216]
];
