// GENERATED by tools/fit_spawn.py from reference/dumps/rooms_select_nonmatching_object (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-18, -15, 1.0, 228, 255, 255],
  [10, 11, 1.0, 255, 203, 234],
  [23, 25, 1.0, 255, 213, 241]
];
