// GENERATED by tools/fit_spawn.py from reference/dumps/rooms_collect_good_objects_test (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-10, -9, 0.8, 255, 224, 255],
  [-6, -4, 0.35, 229, 224, 255],
  [17, 20, 1.0, 254, 255, 255],
  [29, 32, 1.0, 255, 255, 255]
];
