// GENERATED by tools/fit_spawn.py from reference/dumps/skymaze_irreversible_path_hard (frame 0). DO NOT EDIT.
// The spawn effect's bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).
const DM_SPAWN0 = [
  [-25, -20, 1.0, 243, 255, 255]
];
