#!/usr/bin/env python
"""Generate roms/NOTICE.md from manifest.json: every ROM's file, sha1, size, game, authors, release,
Octax module, whether Octax modified it (.8o source in its roms/), and whether Octax's own metadata
sha1 matched the file. Run from anywhere:  uv run --no-sync python tools/rom_notice.py [--check]
"""
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
FAMILY = HERE.parent
# Octax-modified builds: their .8o sources ship in Octax's roms/ (manifest reference.license)
OCTAX_MODIFIED = {"cavern", "spacejam", "flight_runner", "target_shooter"}


def render() -> str:
    m = json.loads((FAMILY / "manifest.json").read_text())
    ref = m["reference"]
    rows = []
    for game, g in sorted(m["games"].items()):
        targets = [(g["rom"], g["sha1"], game)] if "rom" in g else [(lv["rom"], lv["sha1"], lv["env_id"]) for lv in g["levels"].values()]
        for rom, sha, env_id in targets:
            actual = hashlib.sha1((FAMILY / "roms" / rom).read_bytes()).hexdigest()
            assert actual == sha == m["roms"][rom]["sha1"], (rom, actual, sha)
            meta_ok = sha in g["metadata_roms"]
            rows.append((rom, sha, m["roms"][rom]["bytes"], env_id, g["title"], ", ".join(g["authors"]) or "unknown", g["release"] or "?",
                         g["module"], "yes" if game in OCTAX_MODIFIED else "no", "yes" if meta_ok else "no"))
    out = [f"# ROM notice — `parity/chip8/roms/`",
           "",
           f"Every file here is a byte-for-byte copy from the Octax repository ({ref['repo']}, branch {ref['branch']}, commit `{ref['commit']}`, cloned {ref['cloned']}). Octax's code is MIT; its four modified builds (cavern, spacejam, flightrunner, target_shooter) ship with `.8o` sources under that license. The other ROMs are hobbyist / public-domain CHIP-8 programs whose authorship Octax records in each game module's `metadata`; that authorship is reproduced below. Human decision 2026-09-19 (PLAN.md section 9 Q3): keep the ROMs in the repo with this notice. If an author objects, remove the ROM, its `games/<game>.json` and its `dist/` bundle.",
           "",
           "`meta sha1 ok` says whether the sha1 Octax's own metadata gives for the file matches the file (it does not for flight_runner, spacejam, worm, and the levelled games' metadata refers to other files). The bytes in the pinned commit are the reference either way.",
           "",
           "| file | sha1 | bytes | game | title | authors | release | Octax module | modified by Octax | meta sha1 ok |",
           "|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    out.append("")
    out.append(f"{len(rows)} ROM files, {len(m['games'])} game modules. Generated by tools/rom_notice.py from manifest.json; do not edit by hand.")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = render()
    path = FAMILY / "roms" / "NOTICE.md"
    if "--check" in sys.argv:
        sys.exit(0 if path.exists() and path.read_text() == text else 1)
    path.write_text(text)
    print(path)
