"""V1b: fit each level's frame-0 spawn bands (DM_SPAWN0) to its oracle dumps.

    uv run --no-sync python tools/fit_spawn.py [level ...] [--check]

DMLab draws a teleport-in effect at spawn: rings around the player, so on
screen bands at a fixed u = (row - 32) / sqrt(1 + ((col - 32) / 32)^2) (height
over distance on a cylinder round the eye), at any pose. Where they are at
frame 0 differs by level (the effect's phase when the first observation is
taken), so each level gets its own bands, fitted from its 32 frame-0 dumps:

  * the port's frame 0 without bands (tools/perceptual_frames.mjs --no-spawn);
  * per 1-unit u bin, the opacity a (0.05 steps) and colour H (per-channel
    median) that minimise |oracle - ((1 - a) * port + a * H)|;
  * kept only where the fit lowers the bin's error by >= MIN_GAIN and H is
    near-white, every channel >= WHITE (the rings are white to pink-white
    in the probe; other colours are the scene's own differences, and in
    rooms, whose spawn pose barely varies by seed, they would repaint the
    oracle's walls);
  * neighbouring kept bins with the same opacity and a colour within MERGE
    become one band.

Writes src/spawn/<level>.js. The bands are our own drawing (flat colour
bands), not DMLab's effect image.
"""
from __future__ import annotations

import base64
import io
import json
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).resolve().parent.parent
OUT_DIR = HERE / 'src' / 'spawn'
MIN_GAIN = 1.0      # mean absolute error, 0-255, within the bin
WHITE = 200         # the minimum channel of a ring colour
MERGE = 16.0        # max per-channel colour difference to merge bins


def hud_mask():
    m = np.zeros((64, 64), bool)
    m[56:64, 0:37] = True
    m[52:58, 59:64] = True
    m[0:2, 61:64] = True
    return m


def frame0_pairs(level):
    with tempfile.NamedTemporaryFile(suffix='.json', delete=False) as fh:
        tmp = Path(fh.name)
    subprocess.run(['node', str(HERE / 'tools' / 'perceptual_frames.mjs'), level, str(tmp), '--no-spawn'],
                   check=True, capture_output=True, text=True)
    port = json.loads(tmp.read_text())
    tmp.unlink()
    O, P = [], []
    for f in sorted((HERE / 'reference' / 'dumps' / level).glob('*.json'), key=lambda p: int(p.stem)):
        d = json.loads(f.read_text())
        fr, pf = d['frames'][0], port[str(d['seed'])][0]
        assert fr['frame'] == 0 and pf['frame'] == 0
        O.append(np.asarray(Image.open(io.BytesIO(base64.b64decode(fr['png']))).convert('RGB')))
        P.append(np.frombuffer(base64.b64decode(pf['rgb']), np.uint8).reshape(64, 64, 3))
    return np.stack(O).astype(np.float32), np.stack(P).astype(np.float32)


def fit(level):
    O, P = frame0_pairs(level)
    y, x = np.mgrid[0:64, 0:64] + 0.5
    u = (y - 32) / np.sqrt(1 + ((x - 32) / 32) ** 2)
    hud = hud_mask()
    bins = []
    for lo in range(-32, 32):
        m = (u >= lo) & (u < lo + 1) & ~hud
        if not m.any():
            continue
        o, p = O[:, m].reshape(-1, 3), P[:, m].reshape(-1, 3)
        base = np.abs(o - p).mean()
        best = (base, 0.0, None)
        for a in np.arange(0.05, 1.0001, 0.05):
            H = np.clip(np.median((o - (1 - a) * p) / a, 0), 0, 255).round()
            e = np.abs(o - ((1 - a) * p + a * H)).mean()
            if e < best[0]:
                best = (e, round(float(a), 2), H)
        if best[2] is not None and base - best[0] >= MIN_GAIN and best[2].min() >= WHITE:
            bins.append([lo, lo + 1, best[1], *[int(v) for v in best[2]]])
    bands = []
    for b in bins:
        if bands and bands[-1][1] == b[0] and bands[-1][2] == b[2] and \
                max(abs(bands[-1][3 + i] - b[3 + i]) for i in range(3)) <= MERGE:
            bands[-1][1] = b[1]
        else:
            bands.append(list(b))
    return bands


def render(level, bands):
    rows = ',\n'.join(f'  {json.dumps(b)}' for b in bands)
    return (f'// GENERATED by tools/fit_spawn.py from reference/dumps/{level} (frame 0). DO NOT EDIT.\n'
            '// The spawn effect\'s bands at frame 0: [u0, u1, opacity, r, g, b] (80_render.js).\n'
            f'const DM_SPAWN0 = [{chr(10) + rows + chr(10) if bands else ""}];\n')


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    levels = args or sorted(p.name for p in (HERE / 'reference' / 'dumps').iterdir() if p.is_dir())
    OUT_DIR.mkdir(exist_ok=True)
    stale = []
    for level in levels:
        text = render(level, fit(level))
        out = OUT_DIR / f'{level}.js'
        if '--check' in sys.argv:
            if not out.exists() or out.read_text() != text:
                stale.append(level)
            continue
        out.write_text(text)
        print(level, text.count('\n  ['), 'bands', flush=True)
    if stale:
        sys.exit('stale spawn bands: ' + ', '.join(stale))


if __name__ == '__main__':
    main()
