// AUTO-GENERATED by node-gym-dmlab/tools/build-tester.mjs from levels/rooms_watermaze.mjs — do not edit.
(() => {
  var __defProp = Object.defineProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };

  // levels/rooms_watermaze.mjs
  var rooms_watermaze_exports = {};
  __export(rooms_watermaze_exports, {
    config: () => config,
    createCpuInstance: () => createCpuInstance,
    createInstance: () => createInstance,
    getGameState: () => getGameState,
    render: () => render,
    resetGame: () => resetGame,
    setup: () => setup,
    update: () => update
  });

  // src/maze.mjs
  var CELL = {
    WALL: "wall",
    FLOOR: "floor"
  };
  function parseMaze(text) {
    const rawLines = text.replace(/^\n/, "").replace(/\n[ \t]*$/, "").split("\n");
    const height = rawLines.length;
    const width = rawLines.reduce((m, l) => Math.max(m, l.length), 0);
    const cells = [];
    const spawns = [];
    const apples = [];
    const goals = [];
    const floors = [];
    const walls = [];
    for (let row = 0; row < height; row++) {
      const line = rawLines[row];
      const cellRow = [];
      for (let col = 0; col < width; col++) {
        const ch = col < line.length ? line[col] : " ";
        if (ch === "*") {
          cellRow.push(CELL.WALL);
          walls.push({ row, col });
          continue;
        }
        cellRow.push(CELL.FLOOR);
        floors.push({ row, col });
        if (ch === "P") spawns.push({ row, col });
        else if (ch === "A") apples.push({ row, col });
        else if (ch === "G") goals.push({ row, col });
      }
      cells.push(cellRow);
    }
    return { width, height, cells, spawns, apples, goals, floors, walls };
  }

  // src/geometry.mjs
  var CELL_SIZE = 1;
  var WALL_HEIGHT = 1;
  function cellToWorld(row, col) {
    return { x: col * CELL_SIZE, z: row * CELL_SIZE };
  }
  function buildMazeGeometry(THREE, scene, maze, theme) {
    const group = new THREE.Group();
    const w = maze.width * CELL_SIZE;
    const d = maze.height * CELL_SIZE;
    const cx = (maze.width - 1) * CELL_SIZE / 2;
    const cz = (maze.height - 1) * CELL_SIZE / 2;
    const floorGeo = new THREE.PlaneGeometry(w, d);
    const floor = new THREE.Mesh(floorGeo, theme.floor);
    floor.rotation.x = -Math.PI / 2;
    floor.position.set(cx, 0, cz);
    group.add(floor);
    const ceil = new THREE.Mesh(floorGeo, theme.ceiling);
    ceil.rotation.x = Math.PI / 2;
    ceil.position.set(cx, WALL_HEIGHT, cz);
    group.add(ceil);
    const wallCells = maze.walls;
    const boxGeo = new THREE.BoxGeometry(CELL_SIZE, WALL_HEIGHT, CELL_SIZE);
    const inst = new THREE.InstancedMesh(boxGeo, theme.wall, wallCells.length);
    const m = new THREE.Matrix4();
    for (let i = 0; i < wallCells.length; i++) {
      const { row, col } = wallCells[i];
      const { x, z } = cellToWorld(row, col);
      m.makeTranslation(x, WALL_HEIGHT / 2, z);
      inst.setMatrixAt(i, m);
    }
    inst.instanceMatrix.needsUpdate = true;
    group.add(inst);
    scene.add(group);
    return {
      group,
      bounds: { minX: -CELL_SIZE / 2, minZ: -CELL_SIZE / 2, maxX: w - CELL_SIZE / 2, maxZ: d - CELL_SIZE / 2 }
    };
  }
  function isWallAtWorld(maze, x, z) {
    const col = Math.round(x / CELL_SIZE);
    const row = Math.round(z / CELL_SIZE);
    if (row < 0 || row >= maze.height || col < 0 || col >= maze.width) return true;
    return maze.cells[row][col] === CELL.WALL;
  }

  // src/controller.mjs
  var UNITS_PER_CELL = 100;
  var G_SPEED = 320 / UNITS_PER_CELL;
  var PM_STOPSPEED = 100 / UNITS_PER_CELL;
  var PM_ACCELERATE = 10;
  var PM_FRICTION = 6;
  var LOOK_DEG_PER_SEC = 6.6;
  var LOOK_RAD_PER_SEC = LOOK_DEG_PER_SEC * Math.PI / 180;
  var PITCH_LIMIT = 89 * Math.PI / 180;
  var PLAYER_RADIUS = 0.15;
  var EYE_HEIGHT = 0.26;
  function canStand(solid, x, z) {
    const r = PLAYER_RADIUS;
    return !solid(x - r, z - r) && !solid(x + r, z - r) && !solid(x - r, z + r) && !solid(x + r, z + r);
  }
  var TESTER_TURN = 280;
  function discreteToVector(a) {
    let lr = 0, move = 0;
    if (a === 1 || a === 5 || a === 7 || a === 11) lr = -TESTER_TURN;
    if (a === 2 || a === 6 || a === 8 || a === 12) lr = TESTER_TURN;
    if (a === 3 || a === 5 || a === 6 || a === 13) move = 1;
    if (a === 4 || a === 7 || a === 8 || a === 14) move = -1;
    return [lr, 0, 0, move, 0, 0, 0];
  }
  function makeController(opts = {}) {
    return {
      x: 0,
      z: 0,
      yaw: 0,
      pitch: 0,
      vx: 0,
      vz: 0,
      // Optional collision override: isSolid(x,z)->bool. Default: grid wall test.
      _isSolid: opts.isSolid || null,
      _gridMaze: null,
      _gridSolid: null,
      // memoised grid predicate (hot path)
      reset(x, z, yaw = 0) {
        this.x = x;
        this.z = z;
        this.yaw = yaw;
        this.pitch = 0;
        this.vx = 0;
        this.vz = 0;
      },
      /** Apply one action for dt seconds, with collision against `maze`. Accepts
       *  either DM Lab's 7-value vector (RL env) or a Discrete(15) integer (the
       *  keyboard tester). */
      update(dt, action, maze) {
        const isVec = Array.isArray(action) || action != null && ArrayBuffer.isView(action);
        const a = isVec ? action : discreteToVector(action | 0);
        this.yaw -= (a[0] || 0) * LOOK_RAD_PER_SEC * dt;
        this.pitch += (a[1] || 0) * LOOK_RAD_PER_SEC * dt;
        if (this.pitch > PITCH_LIMIT) this.pitch = PITCH_LIMIT;
        if (this.pitch < -PITCH_LIMIT) this.pitch = -PITCH_LIMIT;
        const fx = -Math.sin(this.yaw), fz = -Math.cos(this.yaw);
        const rx = Math.cos(this.yaw), rz = -Math.sin(this.yaw);
        const move = Math.max(-1, Math.min(1, a[3] || 0));
        const strafe = Math.max(-1, Math.min(1, a[2] || 0));
        const speed = Math.hypot(this.vx, this.vz);
        if (speed > 0) {
          const control = speed < PM_STOPSPEED ? PM_STOPSPEED : speed;
          let newspeed = speed - control * PM_FRICTION * dt;
          if (newspeed < 0) newspeed = 0;
          newspeed /= speed;
          this.vx *= newspeed;
          this.vz *= newspeed;
        }
        let wx = fx * move + rx * strafe, wz = fz * move + rz * strafe;
        const wmag = Math.hypot(wx, wz);
        if (wmag > 0) {
          wx /= wmag;
          wz /= wmag;
        }
        const wishspeed = G_SPEED * Math.max(Math.abs(move), Math.abs(strafe));
        const cur = this.vx * wx + this.vz * wz;
        const add = wishspeed - cur;
        if (add > 0) {
          let accel = PM_ACCELERATE * dt * wishspeed;
          if (accel > add) accel = add;
          this.vx += accel * wx;
          this.vz += accel * wz;
        }
        if (!this._isSolid && this._gridMaze !== maze) {
          this._gridMaze = maze;
          this._gridSolid = (x, z) => isWallAtWorld(maze, x, z);
        }
        const solid = this._isSolid || this._gridSolid;
        const dx = this.vx * dt, dz = this.vz * dt;
        if (canStand(solid, this.x + dx, this.z)) this.x += dx;
        else this.vx = 0;
        if (canStand(solid, this.x, this.z + dz)) this.z += dz;
        else this.vz = 0;
      },
      /** Write the controller pose onto a Three.js camera. */
      applyToCamera(camera) {
        camera.position.set(this.x, EYE_HEIGHT, this.z);
        camera.rotation.set(this.pitch, this.yaw, 0, "YXZ");
      }
    };
  }

  // src/theme.mjs
  function makeTheme(THREE) {
    return {
      background: new THREE.Color(7048447),
      // sky
      fog: new THREE.Fog(7048447, 6, 26),
      wall: new THREE.MeshLambertMaterial({ color: 11975878 }),
      floor: new THREE.MeshLambertMaterial({ color: 3356479 }),
      ceiling: new THREE.MeshLambertMaterial({ color: 9081763 }),
      apple: new THREE.MeshLambertMaterial({ color: 3066944, emissive: 872472 }),
      goal: new THREE.MeshLambertMaterial({ color: 16768e3, emissive: 6702080 })
    };
  }

  // src/watermaze.mjs
  var DEFAULT_SPAWN_RADIUS = 5.8;
  var PLATFORM_RADIUS = 0.6;
  var REWARD_LIMIT = 5;
  var EPISODE_SECONDS = 120;
  var RISE_HEIGHT = 0.96;
  var RISE_SPEED = 7;
  var PLATFORM_HOLD_SECONDS = 1.5;
  var S2 = Math.SQRT1_2;
  var CUES = [
    { dir: "N", ux: 0, uz: -1, color: [230, 57, 70] },
    // red
    { dir: "NE", ux: S2, uz: -S2, color: [255, 140, 0] },
    // orange
    { dir: "E", ux: 1, uz: 0, color: [255, 209, 0] },
    // yellow
    { dir: "SE", ux: S2, uz: S2, color: [46, 204, 64] },
    // green
    { dir: "S", ux: 0, uz: 1, color: [0, 209, 209] },
    // cyan
    { dir: "SW", ux: -S2, uz: S2, color: [58, 134, 255] },
    // blue
    { dir: "W", ux: -1, uz: 0, color: [170, 80, 255] },
    // purple
    { dir: "NW", ux: -S2, uz: -S2, color: [240, 240, 240] }
    // white
  ];
  function cueInset(width, height) {
    return (Math.min(width, height) - 1) / 2 - 2.4;
  }
  function cuePositions(cx, cz, radius) {
    return CUES.map((c) => ({ dir: c.dir, x: cx + c.ux * radius, z: cz + c.uz * radius, color: c.color }));
  }
  var WALL_RADIUS = 7.68;
  var WALL_HEIGHT_CELLS = 2;
  var CUE_RADIUS = 7.6;
  var CUE_Y = 0.96;
  var CUE_W = 0.9;
  var CUE_H = 0.7;
  var AGENT_SPAWN_RADIUS = 7.2;
  function circleSolid(cx, cz, radius) {
    return (x, z) => Math.hypot(x - cx, z - cz) >= radius;
  }
  function makeCircularArena(floorRadius) {
    const gridR = Math.ceil(floorRadius) + 2;
    const size = 2 * gridR + 1;
    const c = gridR;
    const rows = [];
    for (let r = 0; r < size; r++) {
      let line = "";
      for (let col = 0; col < size; col++) {
        line += Math.hypot(r - c, col - c) <= floorRadius ? " " : "*";
      }
      rows.push(line);
    }
    return "\n" + rows.join("\n") + "\n";
  }
  function makeWatermazeRules({
    cx,
    cz,
    spawnRadius = DEFAULT_SPAWN_RADIUS,
    // platform placement (DM Lab 580u)
    agentSpawnRadius = spawnRadius,
    // where the agent (re)spawns on the rim
    platformRadius = PLATFORM_RADIUS,
    rewardLimit = REWARD_LIMIT,
    holdSeconds = PLATFORM_HOLD_SECONDS,
    riseHeight = RISE_HEIGHT,
    riseSpeed = RISE_SPEED
  } = {}) {
    const platformR2 = platformRadius * platformRadius;
    let platform = null;
    let found = 0;
    let mode = "SEEK";
    let mountT = 0;
    const faceCentre = (x, z) => Math.atan2(x - cx, z - cz);
    const riseAt = (t) => Math.min(riseHeight, riseSpeed * t);
    return {
      /** Place the hidden platform (uniform over the disc of radius spawnRadius). */
      reset() {
        const a = Math.random() * 2 * Math.PI;
        const r = spawnRadius * Math.sqrt(Math.random());
        platform = { x: cx + r * Math.cos(a), z: cz + r * Math.sin(a) };
        found = 0;
        mode = "SEEK";
        mountT = 0;
        return platform;
      },
      /** A fresh spawn on the rim, oriented toward the centre. */
      rimSpawn() {
        const a = Math.random() * 2 * Math.PI;
        const x = cx + agentSpawnRadius * Math.cos(a);
        const z = cz + agentSpawnRadius * Math.sin(a);
        return { x, z, yaw: faceCentre(x, z) };
      },
      get platform() {
        return platform;
      },
      get found() {
        return found;
      },
      get mounted() {
        return mode === "MOUNTED";
      },
      get eyeOffset() {
        return mode === "MOUNTED" ? riseAt(mountT) : 0;
      },
      update(px, pz, dt) {
        if (mode === "MOUNTED") {
          mountT += dt;
          if (mountT >= holdSeconds) {
            if (found >= rewardLimit) {
              mode = "DONE";
              return { reward: 0, mounted: false, eyeOffset: 0, done: true, relocate: null };
            }
            mode = "SEEK";
            return { reward: 0, mounted: false, eyeOffset: 0, done: false, relocate: this.rimSpawn() };
          }
          return { reward: 0, mounted: true, eyeOffset: riseAt(mountT), done: false, relocate: null };
        }
        if (mode === "DONE") {
          return { reward: 0, mounted: false, eyeOffset: 0, done: true, relocate: null };
        }
        const dx = px - platform.x;
        const dz = pz - platform.z;
        if (dx * dx + dz * dz < platformR2) {
          found += 1;
          mode = "MOUNTED";
          mountT = 0;
          return { reward: 1, mounted: true, eyeOffset: 0, done: false, relocate: null, justMounted: true };
        }
        return { reward: 0, mounted: false, eyeOffset: 0, done: false, relocate: null };
      }
    };
  }

  // src/watermaze-factory.mjs
  function createWatermazeApi(config2) {
    const maze = parseMaze(config2.entityLayer);
    const cx = (maze.width - 1) / 2;
    const cz = (maze.height - 1) / 2;
    const spawnRadius = config2.spawnRadius ?? DEFAULT_SPAWN_RADIUS;
    const platformRadius = config2.platformRadius ?? PLATFORM_RADIUS;
    const rewardLimit = config2.rewardLimit ?? REWARD_LIMIT;
    const episodeSeconds = config2.episodeLengthSeconds ?? EPISODE_SECONDS;
    const showPlatform = config2.showPlatform ?? false;
    const cueRing = config2.cueRadius ?? cueInset(maze.width, maze.height);
    const cueY = config2.cueY ?? CUE_Y, cueW = config2.cueW ?? CUE_W, cueH = config2.cueH ?? CUE_H;
    const circular = config2.circular || null;
    const rules = makeWatermazeRules({
      cx,
      cz,
      spawnRadius,
      platformRadius,
      rewardLimit,
      agentSpawnRadius: config2.agentSpawnRadius ?? spawnRadius
    });
    let THREE, renderer, scene, camera, theme, controller;
    let platformMesh = null;
    let score = 0;
    let gameState = "PLAYING";
    let time = 0;
    let eyeOffset = 0;
    function setup2({ THREE: T, renderer: r, width, height }) {
      THREE = T;
      renderer = r;
      theme = makeTheme(THREE);
      scene = new THREE.Scene();
      scene.background = theme.background;
      scene.fog = theme.fog;
      camera = new THREE.PerspectiveCamera(90, width / height, 0.02, 50);
      camera.rotation.order = "YXZ";
      scene.add(new THREE.AmbientLight(16777215, 0.65));
      const dir = new THREE.DirectionalLight(16777215, 0.7);
      dir.position.set(0.5, 1, 0.25);
      scene.add(dir);
      if (circular) {
        const wallH = circular.wallHeight, segs = circular.segments ?? 64;
        const floor = new THREE.Mesh(new THREE.CircleGeometry(circular.radius, segs), theme.floor);
        floor.rotation.x = -Math.PI / 2;
        floor.position.set(cx, 0, cz);
        scene.add(floor);
        const wallGeo = new THREE.CylinderGeometry(circular.radius, circular.radius, wallH, segs, 1, true);
        const wall = new THREE.Mesh(wallGeo, new THREE.MeshLambertMaterial({ color: 11975878, side: THREE.BackSide }));
        wall.position.set(cx, wallH / 2, cz);
        scene.add(wall);
      } else {
        buildMazeGeometry(THREE, scene, maze, theme);
      }
      const cueGeo = new THREE.BoxGeometry(cueW, cueH, 0.12);
      for (const c of cuePositions(cx, cz, cueRing)) {
        const hex = c.color[0] << 16 | c.color[1] << 8 | c.color[2];
        const mat = new THREE.MeshLambertMaterial({ color: hex, emissive: hex, emissiveIntensity: 0.3 });
        const m = new THREE.Mesh(cueGeo, mat);
        m.position.set(c.x, cueY, c.z);
        m.lookAt(cx, cueY, cz);
        scene.add(m);
      }
      const discGeo = new THREE.CylinderGeometry(platformRadius, platformRadius, 0.04, 24);
      platformMesh = new THREE.Mesh(discGeo, new THREE.MeshBasicMaterial({ color: 65484, transparent: true, opacity: 0.35 }));
      platformMesh.visible = showPlatform;
      scene.add(platformMesh);
      controller = makeController(circular ? { isSolid: circleSolid(cx, cz, circular.radius) } : {});
    }
    function resetGame2() {
      score = 0;
      gameState = "PLAYING";
      time = 0;
      eyeOffset = 0;
      const p = rules.reset();
      platformMesh.position.set(p.x, 0.02, p.z);
      platformMesh.visible = showPlatform;
      const s = rules.rimSpawn();
      controller.reset(s.x, s.z, s.yaw);
      controller.applyToCamera(camera);
    }
    function update2(dt, action) {
      if (gameState !== "PLAYING") return;
      time += dt;
      if (rules.mounted) {
        const p = rules.platform;
        controller.x = p.x;
        controller.z = p.z;
        controller.vx = 0;
        controller.vz = 0;
      } else {
        controller.update(dt, action !== void 0 ? action : globalThis.currentAction, maze);
      }
      const res = rules.update(controller.x, controller.z, dt);
      if (res.justMounted) {
        const p = rules.platform;
        controller.x = p.x;
        controller.z = p.z;
        controller.vx = 0;
        controller.vz = 0;
      }
      if (res.reward) score += res.reward;
      if (res.done) {
        gameState = "WIN";
      } else if (res.relocate) {
        controller.reset(res.relocate.x, res.relocate.z, res.relocate.yaw);
      }
      eyeOffset = res.eyeOffset;
      controller.applyToCamera(camera);
      camera.position.y = EYE_HEIGHT + eyeOffset;
      if (gameState === "PLAYING" && time >= episodeSeconds) gameState = "TIMEOUT";
    }
    function render2() {
      renderer.render(scene, camera);
    }
    function getGameState2() {
      return { score, lives: 1, gameState };
    }
    return {
      setup: setup2,
      update: update2,
      render: render2,
      resetGame: resetGame2,
      getGameState: getGameState2,
      getScene: () => scene,
      getCamera: () => camera
    };
  }

  // src/three-cpu-env.mjs
  var FIXED_DT = 1 / 60;
  var APPLE_REWARD = 1;
  var GOAL_REWARD = 10;
  var PICKUP_R2 = 0.45 * 0.45;
  var GOAL_R2 = 0.5 * 0.5;
  function mulberry32(seed) {
    let t = seed >>> 0;
    return () => {
      t += 1831565813;
      let n = Math.imul(t ^ t >>> 15, t | 1);
      n ^= n + Math.imul(n ^ n >>> 7, n | 61);
      return ((n ^ n >>> 14) >>> 0) / 4294967296;
    };
  }
  function buildScene(THREE, maze, config2 = {}) {
    const scene = new THREE.Scene();
    const W = maze.width, H = maze.height, cx = (W - 1) / 2, cz = (H - 1) / 2;
    if (config2.circular) {
      const { radius, wallHeight, segments = 64 } = config2.circular;
      const ring = [];
      for (let i = 0; i < segments; i++) {
        const a = i / segments * 2 * Math.PI;
        ring.push([cx + radius * Math.cos(a), cz + radius * Math.sin(a)]);
      }
      const wallPos = [], floorPos = [];
      const tri = (arr, a, b, c) => arr.push(...a, ...b, ...c);
      for (let i = 0; i < segments; i++) {
        const [x0, z0] = ring[i], [x1, z1] = ring[(i + 1) % segments];
        tri(wallPos, [x0, 0, z0], [x1, 0, z1], [x1, wallHeight, z1]);
        tri(wallPos, [x0, 0, z0], [x1, wallHeight, z1], [x0, wallHeight, z0]);
        tri(floorPos, [cx, 0, cz], [x0, 0, z0], [x1, 0, z1]);
      }
      const mk = (p, color) => {
        const g = new THREE.BufferGeometry();
        g.setAttribute("position", new THREE.Float32BufferAttribute(p, 3));
        const m = new THREE.Mesh(g, new THREE.MeshBasicMaterial({ color, side: THREE.DoubleSide }));
        m.userData.static = true;
        scene.add(m);
      };
      mk(floorPos, 3356479);
      mk(wallPos, 11975878);
    } else {
      const isWall = (r, c) => r < 0 || c < 0 || r >= maze.height || c >= maze.width || maze.cells[r][c] === CELL.WALL;
      const pos = [];
      const face = (a, b, c, d) => {
        pos.push(...a, ...b, ...c, ...a, ...c, ...d);
      };
      for (let r = 0; r < maze.height; r++) for (let c = 0; c < maze.width; c++) {
        if (maze.cells[r][c] !== CELL.WALL) continue;
        const x0 = c - 0.5, x1 = c + 0.5, z0 = r - 0.5, z1 = r + 0.5, y0 = 0, y1 = WALL_HEIGHT;
        if (!isWall(r, c - 1)) face([x0, y0, z0], [x0, y0, z1], [x0, y1, z1], [x0, y1, z0]);
        if (!isWall(r, c + 1)) face([x1, y0, z1], [x1, y0, z0], [x1, y1, z0], [x1, y1, z1]);
        if (!isWall(r - 1, c)) face([x1, y0, z0], [x0, y0, z0], [x0, y1, z0], [x1, y1, z0]);
        if (!isWall(r + 1, c)) face([x0, y0, z1], [x1, y0, z1], [x1, y1, z1], [x0, y1, z1]);
      }
      const wallGeo = new THREE.BufferGeometry();
      wallGeo.setAttribute("position", new THREE.Float32BufferAttribute(pos, 3));
      const walls = new THREE.Mesh(wallGeo, new THREE.MeshBasicMaterial({ color: 11975878, side: THREE.DoubleSide }));
      walls.userData.static = true;
      scene.add(walls);
      const floor = new THREE.Mesh(new THREE.PlaneGeometry(W, H), new THREE.MeshBasicMaterial({ color: 3356479, side: THREE.DoubleSide }));
      floor.rotation.x = -Math.PI / 2;
      floor.position.set(cx, 0, cz);
      floor.userData.static = true;
      scene.add(floor);
      const ceil = new THREE.Mesh(new THREE.PlaneGeometry(W, H), new THREE.MeshBasicMaterial({ color: 9081763, side: THREE.DoubleSide }));
      ceil.rotation.x = Math.PI / 2;
      ceil.position.set(cx, WALL_HEIGHT, cz);
      ceil.userData.static = true;
      scene.add(ceil);
    }
    if (config2.watermaze) {
      const ring = config2.cueRadius ?? cueInset(W, H);
      const cueY = config2.cueY ?? CUE_Y, cueW = config2.cueW ?? CUE_W, cueH = config2.cueH ?? CUE_H;
      const cueGeo = new THREE.BoxGeometry(cueW, cueH, 0.12);
      for (const c of cuePositions(cx, cz, ring)) {
        const hex = c.color[0] << 16 | c.color[1] << 8 | c.color[2];
        const m = new THREE.Mesh(cueGeo, new THREE.MeshBasicMaterial({ color: hex }));
        m.position.set(c.x, cueY, c.z);
        m.lookAt(cx, cueY, cz);
        m.userData.static = true;
        scene.add(m);
      }
    }
    return scene;
  }
  function createThreeCpuEnv({ THREE, renderer, config: config2, width = 84, height = 84, maxSteps = 3600 }) {
    const maze = parseMaze(config2.entityLayer);
    const appleCount = config2.appleCount ?? 8;
    const goalEndsEpisode = config2.goalEndsEpisode ?? true;
    const goalMinManhattan = config2.goalMinManhattan ?? Math.floor((maze.width + maze.height) / 3);
    const controller = makeController(config2.circular ? { isSolid: circleSolid((maze.width - 1) / 2, (maze.height - 1) / 2, config2.circular.radius) } : {});
    const watermaze = config2.watermaze ? makeWatermazeRules({
      cx: (maze.width - 1) / 2,
      cz: (maze.height - 1) / 2,
      spawnRadius: config2.spawnRadius ?? DEFAULT_SPAWN_RADIUS,
      agentSpawnRadius: config2.agentSpawnRadius ?? config2.spawnRadius ?? DEFAULT_SPAWN_RADIUS,
      platformRadius: config2.platformRadius ?? PLATFORM_RADIUS,
      rewardLimit: config2.rewardLimit ?? REWARD_LIMIT
    }) : null;
    const scene = buildScene(THREE, maze, config2);
    const camera = new THREE.PerspectiveCamera(90, width / height, 0.02, 60);
    camera.rotation.order = "YXZ";
    const appleMeshes = [];
    const appleGeo = new THREE.SphereGeometry(0.2, 8, 6);
    for (let i = 0; i < 24; i++) {
      const m = new THREE.Mesh(appleGeo, new THREE.MeshBasicMaterial({ color: 3066944 }));
      m.visible = false;
      scene.add(m);
      appleMeshes.push(m);
    }
    const goalMesh = new THREE.Mesh(new THREE.OctahedronGeometry(0.32), new THREE.MeshBasicMaterial({ color: 16768e3 }));
    goalMesh.visible = false;
    scene.add(goalMesh);
    let score = 0, gameState = "PLAYING", steps = 0, lastScore = 0, max = maxSteps;
    let goal = null, apples = [], eyeOffset = 0;
    const randFloor = () => maze.floors[Math.floor(Math.random() * maze.floors.length)];
    function pickRandom(n, exclude) {
      const taken = new Set(exclude.map((c) => c.row + "," + c.col)), o = [];
      for (let t = 0; t < n * 40 && o.length < n; t++) {
        const c = randFloor(), k = c.row + "," + c.col;
        if (taken.has(k)) continue;
        taken.add(k);
        o.push(c);
      }
      return o;
    }
    function render2() {
      camera.position.set(controller.x, EYE_HEIGHT + eyeOffset, controller.z);
      camera.rotation.set(controller.pitch, controller.yaw, 0, "YXZ");
      return renderer.render(scene, camera);
    }
    function reset(seed, maxStepsOverride) {
      if (maxStepsOverride) max = maxStepsOverride;
      Math.random = mulberry32((seed ?? 0) >>> 0);
      score = 0;
      gameState = "PLAYING";
      steps = 0;
      lastScore = 0;
      if (watermaze) {
        watermaze.reset();
        const s = watermaze.rimSpawn();
        controller.reset(s.x, s.z, s.yaw);
        eyeOffset = 0;
        for (const m of appleMeshes) m.visible = false;
        goalMesh.visible = false;
        goal = null;
        apples = [];
        return render2();
      }
      const spawnCell = maze.spawns.length ? maze.spawns[Math.floor(Math.random() * maze.spawns.length)] : randFloor();
      const sw = cellToWorld(spawnCell.row, spawnCell.col);
      controller.reset(sw.x, sw.z, Math.random() * Math.PI * 2);
      let goalCell;
      if (maze.goals.length) goalCell = maze.goals[Math.floor(Math.random() * maze.goals.length)];
      else {
        for (let t = 0; t < 200; t++) {
          const c = randFloor();
          goalCell = c;
          if (Math.abs(c.row - spawnCell.row) + Math.abs(c.col - spawnCell.col) >= goalMinManhattan) break;
        }
      }
      const gw = cellToWorld(goalCell.row, goalCell.col);
      goal = { x: gw.x, z: gw.z };
      goalMesh.position.set(goal.x, 0.4, goal.z);
      goalMesh.visible = true;
      const cells = maze.apples.length ? maze.apples.slice(0, 24) : pickRandom(appleCount, [spawnCell, goalCell]);
      apples = [];
      for (let i = 0; i < appleMeshes.length; i++) {
        if (i < cells.length) {
          const w = cellToWorld(cells[i].row, cells[i].col);
          appleMeshes[i].position.set(w.x, 0.25, w.z);
          appleMeshes[i].visible = true;
          apples.push({ x: w.x, z: w.z, mesh: appleMeshes[i] });
        } else appleMeshes[i].visible = false;
      }
      return render2();
    }
    function step(action, numSteps = 1) {
      let reward = 0, terminated = false, truncated = false;
      const k = numSteps > 0 ? numSteps : 1;
      for (let i = 0; i < k; i++) {
        if (gameState === "PLAYING") {
          if (watermaze) {
            if (watermaze.mounted) {
              const p = watermaze.platform;
              controller.x = p.x;
              controller.z = p.z;
              controller.vx = 0;
              controller.vz = 0;
            } else controller.update(FIXED_DT, action, maze);
            const r = watermaze.update(controller.x, controller.z, FIXED_DT);
            if (r.justMounted) {
              const p = watermaze.platform;
              controller.x = p.x;
              controller.z = p.z;
              controller.vx = 0;
              controller.vz = 0;
            }
            if (r.reward) score += r.reward;
            if (r.done) gameState = "WIN";
            else if (r.relocate) controller.reset(r.relocate.x, r.relocate.z, r.relocate.yaw);
            eyeOffset = r.eyeOffset;
          } else {
            controller.update(FIXED_DT, action, maze);
            const px = controller.x, pz = controller.z;
            for (const a of apples) {
              if (!a.mesh.visible) continue;
              const dx = px - a.x, dz = pz - a.z;
              if (dx * dx + dz * dz < PICKUP_R2) {
                a.mesh.visible = false;
                score += APPLE_REWARD;
              }
            }
            if (goal) {
              const dx = px - goal.x, dz = pz - goal.z;
              if (dx * dx + dz * dz < GOAL_R2) {
                score += GOAL_REWARD;
                if (goalEndsEpisode) gameState = "WIN";
              }
            }
          }
        }
        reward += score - lastScore;
        lastScore = score;
        steps += 1;
        if (gameState !== "PLAYING") {
          terminated = true;
          break;
        }
        if (steps >= max) {
          truncated = true;
          break;
        }
      }
      return { obs: render2(), reward, terminated, truncated, score, gameState, steps };
    }
    return { reset, step, width, height };
  }

  // levels/rooms_watermaze.mjs
  var entityLayer = makeCircularArena(WALL_RADIUS);
  var config = {
    entityLayer,
    watermaze: true,
    circular: { radius: WALL_RADIUS, wallHeight: WALL_HEIGHT_CELLS, segments: 64 },
    spawnRadius: 5.8,
    // hidden platform placement (spawnRadius 580u)
    agentSpawnRadius: AGENT_SPAWN_RADIUS,
    // agent (re)spawn ring near the wall (~720u)
    cueRadius: CUE_RADIUS,
    // distal cue frames just inside the wall (760u)
    cueY: CUE_Y,
    cueW: CUE_W,
    cueH: CUE_H,
    platformRadius: 0.6,
    rewardLimit: 5,
    episodeLengthSeconds: 120,
    showPlatform: false
  };
  var api = createWatermazeApi(config);
  var setup = api.setup;
  var update = api.update;
  var render = api.render;
  var resetGame = api.resetGame;
  var getGameState = api.getGameState;
  function createInstance(opts) {
    const inst = createWatermazeApi(config);
    inst.setup(opts);
    return inst;
  }
  function createCpuInstance(opts) {
    return createThreeCpuEnv({ ...opts, config });
  }

  // levels/tester-entry.mjs
  for (const k of ["setup", "update", "render", "resetGame", "getGameState"]) globalThis[k] = rooms_watermaze_exports[k];
})();
