#!/usr/bin/env python
"""Generate games/NOTICE.md from manifest.json: every corpus game's title, author, dropdown group, source file and
sha256, with the demo folder's license warning and the removal procedure.  uv run --no-sync python tools/game_notice.py [--check]
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
FAMILY = HERE.parent


def render() -> str:
    m = json.loads((FAMILY / "manifest.json").read_text())
    ref = m["reference"]
    out = ["# Game notice — `parity/puzzlescript/games/`", "",
           f"Every `.txt` here is a byte-for-byte copy of a file under `src/demo/` in the PuzzleScript repository ({ref['repo']}, branch {ref['branch']}, commit `{ref['commit']}`, cloned {ref['cloned']}). The engine is MIT. The games are the ones the PuzzleScript editor offers in its example dropdown (`src/editor.html`); the repository's `src/demo/README` says those can be assumed MIT while the other files in that folder are private records of other people's games with no license established, so nothing else from that folder is shipped. Authorship below is each game's own `author` line. If an author objects, remove `games/<game>.txt`, `games/<game>.json` and `dist/ps_<game>.*`, drop the game from `manifest.json`, and rerun `node tests/golden.mjs --write`.",
           "", "| game | title | author | dropdown group | source | sha256 | levels (playable) |", "|---|---|---|---|---|---|---|"]
    for g in m["corpus"]["dropdown_order"]:
        v = m["corpus"]["games"][g]
        out.append(f"| {g} | {v['title']} | {v['author']} | {v['dropdown_group']} | {v['source']} | {v['sha256']} | {v['levels']} ({len(v['playable_levels'])}) |")
    out += ["", f"{len(m['corpus']['games'])} games. Excluded: " + "; ".join(f"{k}: {v}" for k, v in m["excluded"].items()) + ".",
            "", "Generated by tools/game_notice.py from manifest.json; do not edit by hand."]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = render()
    path = FAMILY / "games" / "NOTICE.md"
    if "--check" in sys.argv:
        sys.exit(0 if path.exists() and path.read_text() == text else 1)
    path.write_text(text)
    print(path)
