#!/usr/bin/env node
// precompile_caches.mjs — pre-populate the engine's CACHE_* tables at bundle time so no `new Function` runs.
// The vendored engine generates its matchers/appliers as source strings and compiles them with `new Function`,
// keyed by that source (CACHE_CELLPATTERN_MATCHFUNCTION: a Map keyed by the pattern's bit array). Under QuickJS that
// is the JS parser at game-compile time, and `qjsc -A` cannot AOT what does not exist statically. This tool runs
// each dist bundle under node, plays every playable level with the gate seeds, records every function the caches
// hold, and writes them as ordinary function expressions:
//   twin/caches/ps_<game>.caches.js         the CACHE_* assignments (generated code, committed, hash-checked)
//   twin/caches/manifest.json               per game: dist bundle sha256, cache counts, sha256 of the block
//   node tools/precompile_caches.mjs --write | --check | --assemble <dir>
// --assemble writes <dir>/ps_<game>.js = the dist bundle with the block inserted before the prelude (+ sidecar copy).
// dist/ is never edited. The functions are semantically the engine's own: same parameters, same body, same
// script-scope bindings (a `new Function` body resolves the engine's top-level lets through the global scope, an
// expression in the same script resolves them lexically; both name the same bindings).
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
const HERE = dirname(fileURLToPath(import.meta.url)), ROOT = join(HERE, '..'), OUTDIR = join(ROOT, 'twin', 'caches');
const args = process.argv.slice(2);
const sha256 = (t) => createHash('sha256').update(t).digest('hex');
const MARK = '// ---- src/90_prelude.js ----';
const OBJ_CACHES = ['CACHE_MOVEENTITIESATINDEX', 'CACHE_CALCULATEROWCOLMASKS', 'CACHE_REPOSITIONENTITIESATCELL', 'CACHE_RULE_CELLROWMATCHESFUNCTION',
  'CACHE_CELLPATTERN_REPLACEFUNCTION', 'CACHE_MATCHCELLROW', 'CACHE_MATCHCELLROWWILDCARD', 'CACHE_RULE_APPLYAT', 'CACHE_RESOLVEMOVEMENTS', 'CACHE_RULE_FINDMATCHES'];
const MAP_CACHES = ['CACHE_CELLPATTERN_MATCHFUNCTION'];
const SEEDS = [1, 2, 3, 42, 7, 11, 19, 23];   // the lockstep and golden seeds
const STEPS = 300;
function lcg(seed) { let x = seed >>> 0; return () => { x = (x * 1103515245 + 12345) >>> 0; return x >>> 8; }; }
export function makeContext(counter) {
  const ctx = { console, createCanvas() {}, background() {}, noStroke() {}, fill() {}, rect() {}, drawTiles() {}, keyIsDown: () => false };
  ctx.globalThis = ctx; vm.createContext(ctx);
  if (counter) { const F = vm.runInContext('Function', ctx); const W = function (...a) { counter.n++; return F(...a); }; W.prototype = F.prototype; ctx.Function = W; }
  return ctx;
}
// `new Function(p1, .., body).toString()` is `function anonymous(p1,..\n) {\nbody\n}`: recover (params, body)
function split(fn) {
  const s = fn.toString(); const m = /^function anonymous\(([^)]*)\n\) \{\n([\s\S]*)\n\}$/.exec(s);
  if (!m) throw new Error('unexpected function source: ' + s.slice(0, 80));
  return [m[1], m[2]];
}
export function extract(game) {
  const text = readFileSync(join(ROOT, 'dist', `ps_${game}.js`), 'utf8');
  const ctx = makeContext(null);
  // the caches are script-scope lets: expose them from inside the same script (a scratch copy in memory)
  const probe = `\nglobalThis.__psCaches = { ${[...OBJ_CACHES, ...MAP_CACHES].map(n => `${n}: () => ${n}`).join(', ')} };\n`;
  vm.runInContext(text + probe, ctx, { filename: `ps_${game}.js` });
  ctx.setup();
  const g = ctx.__ps, pl = g.playable();
  for (const lvl of pl) for (const seed of SEEDS) {
    // pick a seed that lands on this level (level = seed % n for level_mode seed), then play
    const s = g.def().level_mode === 'fixed' ? seed : seed + ((lvl - (seed % pl.length)) + pl.length) % pl.length;
    g.reset(s); const rnd = lcg(s * 7919 + 17);
    for (let k = 0; k < STEPS && !g.snap().winning; k++) g.step(rnd() % 6);
  }
  const C = ctx.__psCaches; let out = `// ---- precompiled caches (generated by tools/precompile_caches.mjs; the engine's own generated functions) ----\n`;
  const counts = {};
  for (const n of OBJ_CACHES) { const t = C[n](); const keys = Object.keys(t); counts[n] = keys.length;
    for (const k of keys) { const [params, body] = split(t[k]); out += `${n}[${JSON.stringify(k)}] = function (${params}) {\n${body}\n};\n`; } }
  for (const n of MAP_CACHES) { const t = C[n](); counts[n] = t.size;
    for (const [k, f] of t) { const [params, body] = split(f); out += `${n}.set(${JSON.stringify(k)}, function (${params}) {\n${body}\n});\n`; } }
  return { block: out, counts, dist_sha256: sha256(text) };
}
export function assemble(game, block) {
  const text = readFileSync(join(ROOT, 'dist', `ps_${game}.js`), 'utf8'); const i = text.indexOf(MARK);
  if (i < 0) throw new Error('prelude marker missing in ps_' + game);
  return text.slice(0, i) + block + '\n' + text.slice(i);
}
const games = readdirSync(join(ROOT, 'games')).filter(f => f.endsWith('.json')).map(f => f.slice(0, -5)).sort();
if (args.includes('--write') || args.includes('--check')) {
  const manifest = {}; let bad = 0; const prev = args.includes('--check') && existsSync(join(OUTDIR, 'manifest.json')) ? JSON.parse(readFileSync(join(OUTDIR, 'manifest.json'), 'utf8')) : null;
  mkdirSync(OUTDIR, { recursive: true });
  for (const game of games) {
    const { block, counts, dist_sha256 } = extract(game);
    const total = Object.values(counts).reduce((a, b) => a + b, 0);
    manifest[game] = { dist_sha256, block_sha256: sha256(block), functions: total, counts };
    if (prev) { const p = prev[game]; const cur = existsSync(join(OUTDIR, `ps_${game}.caches.js`)) ? readFileSync(join(OUTDIR, `ps_${game}.caches.js`), 'utf8') : '';
      if (!p || p.dist_sha256 !== dist_sha256 || p.block_sha256 !== sha256(block) || sha256(cur) !== sha256(block)) { bad++; console.log(`STALE ${game}`); } }
    else { writeFileSync(join(OUTDIR, `ps_${game}.caches.js`), block); console.log(`${game}: ${total} functions (${Object.entries(counts).map(([k, v]) => k.replace('CACHE_', '') + '=' + v).join(' ')})`); }
  }
  if (prev) { console.log(bad ? `${bad} stale` : `caches fresh (${games.length} games)`); process.exit(bad ? 1 : 0); }
  writeFileSync(join(OUTDIR, 'manifest.json'), JSON.stringify(manifest, null, 1) + '\n');
} else if (args.includes('--assemble')) {
  const dir = args[args.indexOf('--assemble') + 1]; mkdirSync(dir, { recursive: true });
  for (const game of games) {
    writeFileSync(join(dir, `ps_${game}.js`), assemble(game, readFileSync(join(OUTDIR, `ps_${game}.caches.js`), 'utf8')));
    const side = JSON.parse(readFileSync(join(ROOT, 'dist', `ps_${game}.json`), 'utf8')); side.precompiled_caches = true;
    writeFileSync(join(dir, `ps_${game}.json`), JSON.stringify(side, null, 2) + '\n');
  }
  console.log(`assembled ${games.length} precompiled bundles in ${dir}`);
} else { console.error('usage: precompile_caches.mjs --write | --check | --assemble <dir>'); process.exit(2); }
