#!/usr/bin/env bash
# Generate qjs/matter_bundle.h from runtime/vendor/matter.min.js.
#
# Matter.js games (angry_birds, suika) expect a `Matter` global. The node backend
# gets one from node_modules; the QuickJS host has no module loader, so the engine
# is compiled in and eval'd into the context before the game, but only for games
# that reference it (see needs_matter in the hosts).
#
# Regenerated on every build: it is derived, and stale output would silently pin
# an old engine. Not checked in.
set -euo pipefail
cd "$(dirname "$0")"

SRC="../runtime/vendor/matter.min.js"
OUT="qjs/matter_bundle.h"

[ -f "$SRC" ] || { echo "missing $SRC" >&2; exit 1; }

# R"MATTERJS(...)MATTERJS" — the delimiter must not appear in the payload.
if grep -q ')MATTERJS"' "$SRC"; then
  echo "matter.min.js contains the raw-string delimiter; pick another" >&2
  exit 1
fi

{
  echo "// Generated by native/gen_matter_header.sh from runtime/vendor/matter.min.js."
  echo "// Do not edit."
  echo "#pragma once"
  echo 'static const char* MATTER_JS = R"MATTERJS('
  cat "$SRC"
  echo ')MATTERJS";'
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
