"""Ablate one game mechanic and measure what it cost.

Panel C attributes qbert.v2's time to "logic", but that is a RESIDUAL -- whatever
is not a counted p5 command. It does not say enemy AI is responsible; it says we
did not measure what is. Because a PlayTrain environment is editable source, we
can delete one mechanic and measure the difference directly.

Ablation: cap enemy spawning at zero. That removes spawning, the per-enemy
pathfinding search, enemy collision checks, AND the draw calls that render them,
so the delta is the whole cost of "this game has enemies" -- and the draw-call
counter splits that delta into its drawing and non-drawing halves.
"""
import pathlib
import shutil

SRC = pathlib.Path('../playtrain/examples/games/js/qbert.v2.js')
DST_DIR = pathlib.Path('../playtrain/examples/games/probe')
DST = DST_DIR / 'qbert_v2_noenemy.js'

s = SRC.read_text()
old = "if (gameTick % spawnRate === 0 && enemies.length < 20) {"
new = "if (false && gameTick % spawnRate === 0 && enemies.length < 20) {"
assert old in s, "spawn guard not found"
DST.write_text("// ABLATION of qbert.v2 -- enemy spawning disabled. Generated by\n"
               "// tools/ablate_qbert.py; not a catalog game.\n"
               + s.replace(old, new))
# also copy the unmodified original next to it, so both are measured from the
# same directory and nothing else can differ
shutil.copy(SRC, DST_DIR / 'qbert_v2_full.js')
print(f"wrote {DST} and qbert_v2_full.js")
