#!/usr/bin/env node
// Build the in-page game player for the project site.
//
//   node tools/build-embed.mjs --out website/site
//
// Emits, under <out>:
//   player.js          the browser shim bundle (raster.mjs + p5-shim.mjs) with
//                      website/player.mjs appended — one ES module
//   games/<name>.js    each bundled game's source, fetched at runtime
//   games/index.json   the catalog listing, so the page's game pickers cannot
//                      drift from what actually shipped
//
// The shim bundle is the same one tools/build-pages.mjs inlines into the
// standalone tester, so the site's player and `just play` render identically —
// both through PlayTrain's own rasterizer, the renderer the agent trains on.

import { readFileSync, writeFileSync, readdirSync, mkdirSync, copyFileSync, existsSync } from 'fs';
import { dirname, resolve, join } from 'path';
import { fileURLToPath } from 'url';
import { browserShimBundle } from './play-templates.mjs';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function arg(flag, def) {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

const OUT = resolve(arg('--out', join(REPO_ROOT, 'website', 'site')));
const GAMES_DIR = resolve(arg('--games', join(REPO_ROOT, 'examples', 'games', 'js')));
const CONTROLLER = join(REPO_ROOT, 'website', 'player.mjs');

if (!existsSync(GAMES_DIR)) {
  console.error(`games dir not found: ${GAMES_DIR}`);
  process.exit(1);
}

const games = readdirSync(GAMES_DIR)
  .filter((f) => f.endsWith('.js') && !f.endsWith('_dbg.js'))
  .map((f) => f.replace(/\.js$/, ''))
  .sort();

// Matter.js games need the physics global installed before their source runs.
// None of the bundled catalog uses it today; fail loudly rather than shipping a
// game that silently throws in the player.
const needsMatter = games.filter((g) =>
  /\bMatter\./.test(readFileSync(join(GAMES_DIR, `${g}.js`), 'utf8')));
if (needsMatter.length) {
  console.error(`these games need the Matter global, which the in-page player does not install: ${needsMatter.join(', ')}`);
  console.error('inline tools/vendor/matter.min.js into player.js before shipping them.');
  process.exit(1);
}

mkdirSync(join(OUT, 'games'), { recursive: true });
for (const g of games) copyFileSync(join(GAMES_DIR, `${g}.js`), join(OUT, 'games', `${g}.js`));
writeFileSync(join(OUT, 'games', 'index.json'), `${JSON.stringify(games, null, 0)}\n`);

const player = `// Generated by tools/build-embed.mjs — do not edit.
// PlayTrain browser shim (runtime/p5/raster.mjs + p5-shim.mjs) + website/player.mjs.
${browserShimBundle()}

${readFileSync(CONTROLLER, 'utf8')}`;
writeFileSync(join(OUT, 'player.js'), player);

console.log(`player.js + ${games.length} games → ${OUT}`);
